service: car-service

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: us-east-2
  iamRoleStatements:
  - Effect: "Allow"
    Action:
    - dynamodb:Scan
    - dynamodb:GetItem
    Resource: "arn:aws:dynamodb:us-east-2:557382684290:table/Cars"

functions:
  getAllCars:
    handler: handler.getAll
    events:
    - http:
        path: cars
        method: get
        cors: true